"""

Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""

def fibonacci_sequence(limit):
	container = [1,2]
	
	for x in container:
		if x >= limit:
			return container
		container.append(container[len(container) - 1] + container[len(container) - 2])
		

def even_sum_finder(limit):
	y = 0
	container = fibonacci_sequence(limit)
	
	for i in container:
		if i % 2 == 0:
			y += i
	return y

print even_sum_finder(4000000)